### PR TITLE
build from pypi

### PR DESCRIPTION
**Pull request by kain88-de**
see if the pypi source tarball can be used to build a conda-forge binary package.

### CODE REVIEW

**Comment by kain88-de** [comment]
@joaander 

This does an update to the new version as well and builds from the pypi sources. To make a release of the version just merge the PR. You should have the rights to do this.

**Comment by joaander** [comment]
What purpose does building from the pypi distribution serve? I'd prefer to have a single source of truth for releases. The pypi distributions are several steps removed from the main repository and do not include all necessary files, such as the LICENSE (as you made an issue about), documentation, cython source files, etc... that future conda builds may utilize.

**Comment by kain88-de** [comment]
>  the main challenge with using the archives from GitHub (and possibly also others) is they are a bit broken. They don't tend to include submodules. Also they tend to be generated on demand, which can mean the checksum changes. This is kind of a pain. So most people use PyPI or a similar source that has stable checksums and all of the content.
You are of course free to use either. We don't actually enforce one, but some of us encourage PyPI to save you some suffering (and avoiding having to debug these known issues again). :wink:
Of course one can easily avoid these issues if they own the repo by publishing their own tarball with checksum.

This is the answer I got from @jakirkham. So if your bitbucket tarballs are stable with hashing there is no reason to prefer pypi. You can close this if you are reasonable sure that this is the case.

Otherwise for me this was a good check to see it I can compile the pypi release.

**Comment by joaander** [comment]
Thanks for the explanation. Looking into it, pypi tarballs can have hash changes as well over time. I guess the only solution is to self-host curated tarballs on the software's homepage. I will do that and update the conda recipe and pypi packages accordingly.

**Comment by jakirkham** [comment]
Could you please provide an example of PyPI packages’ hashes changing?

**Comment by joaander** [comment]
I don't have any specific examples. My statement was based on misinterpreting pypi packaging guidelines from the Arch Linux Wiki: https://wiki.archlinux.org/index.php/Python_package_guidelines

**Comment by jakirkham** [comment]
I think that they are referring to a URL issue that PyPI had, which we and others complained loudly about. PyPI later fixed the issue.

Have not seen a case personally of hashes changing with PyPI. In fact, they make it basically impossible to change something that was already uploaded.

**Pull request closed without merging**
